### ISSUE TITLE
`getInternetCredentials` throws `accessControl` for `rules:none`

### ISSUE THREAD

**Issue by voxspox** [oblador/react-native-keychain#429]
I want to prevent AUTOMATIC_UPGRADE, thus I call:
```
getInternetCredentials('myserver', { rules: 'none' })
```
as suggested in the docs for getGenericPassword.

This results in an exception:

```
code: "E_UNKNOWN_ERROR"
jsEngine: "hermes"
message: "accessControl"
userInfo: null
nativeStackAndroid:
...
5: Object
  class: "com.oblador.keychain.KeychainModule"
  file: "KeychainModule.java"
  lineNumber: 292
  methodName: "getGenericPassword"
6: Object
  class: "com.oblador.keychain.KeychainModule"
  file: "KeychainModule.java"
  lineNumber: 394
  methodName: "getInternetCredentialsForServer"
```
